### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by alekxeyuk** [alekxeyuk/svelte-crypto-tracker#2]
Features to add

- [ ] Add an input field where the user can write a coin name to filter the results
- [ ] Allow the user to fetch more coins with a “Load More” button
- [ ] Make each coin clickable to show more data on that coin
- [ ] Show a graph of price changes for a specific coin
- [ ] Allow the user to sort the coins by percentage growth or current price
- [x] Deploy the project to Netlify
